version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      aws-sdk:
        patterns:
          - "boto3"
          - "botocore"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
