#cloud-config

bootcmd:
  - dpkg --add-architecture i386

apt:
  preserve_sources_list: false
  sources:
    steam.list:
      source: |
        deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
        deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
      keyid: F24AEA9FB05498B7

package_update: true
packages:
- awscli
- build-essential
- dkms
- gnome-session
- gnome-shell-extension-appindicator
- gnome-terminal
- httpie
- libc6-dev
- libglvnd-dev
- libva-drm2
- libva2
- libvdpau1
- linux-aws
- linux-headers-aws
- nautilus
- pkg-config
- restic
- steam-launcher
- steam-libs-amd64
- steam-libs-i386:i386
- unzip
- xserver-xorg-core
- xserver-xorg-dev

# required for first boot only
fs_setup:
- label: instance_storage
  device: /dev/nvme1n1
  filesystem: ext4

mounts:
- ["/dev/nvme1n1", "/mnt", "ext4", "defaults,nofail,x-systemd.requires=cloud-init.service,x-systemd.makefs", "0", "2"]

users:
- default
- name: sunshine
  gecos: Sunshine
  groups: users, audio, video, plugdev, netdev, input
  shell: /bin/bash

write_files:
- path: /etc/modprobe.d/blacklist.conf
  content: |
    blacklist vga16fb
    blacklist nouveau
    blacklist rivafb
    blacklist nvidiafb
    blacklist rivatv
- path: /etc/modprobe.d/nvidia.conf
  content: |
    options nvidia NVreg_EnableGpuFirmware=0
- path: /etc/gdm3/custom.conf
  content: |
    [daemon]
    WaylandEnable=false
    AutomaticLoginEnable = true
    AutomaticLogin = sunshine
    [security]
    [xdmcp]
    [chooser]
    [debug]
- path: /etc/udev/rules.d/85-sunshine-input.rules
  content: |
    KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
- path: /opt/install_nvidia_driver.sh
  content: |
    #!/bin/bash
    cd /mnt
    aws s3 cp --recursive s3://nvidia-gaming/linux/latest/ .
    unzip *Cloud_Gaming-Linux-Guest-Drivers.zip -d nvidia-drivers
    rm -f *Cloud_Gaming-Linux-Guest-Drivers.zip
    chmod +x ./nvidia-drivers/NVIDIA-Linux-x86_64*-grid.run
    /bin/sh ./nvidia-drivers/NVIDIA-Linux-x86_64*-grid.run --dkms --tmpdir=/mnt --silent
    rm -rf ./nvidia-drivers/
    kversion=$(readlink /boot/initrd.img |sed 's/initrd.img-//g')
    dkms autoinstall -k $kversion
    update-initramfs -k $kversion -u
    cat << EOF | tee -a /etc/nvidia/gridd.conf
    vGamingMarketplace=2
    EOF
    curl -o /etc/nvidia/GridSwCert.txt "https://nvidia-gaming.s3.amazonaws.com/GridSwCert-Archive/GridSwCertLinux_2021_10_2.cert"
    nvidia-smi -q | head
    nvidia-xconfig --preserve-busid --enable-all-gpus
  permissions: '0755'
- path: /etc/systemd/system/mnt.service
  content: |
    [Unit]
    After = network-online.target
    Wants = network-online.target
    [Service]
    Type = oneshot
    RemainAfterExit = yes
    ExecStart = mkdir -p /mnt/sunshine
    ExecStart = chown sunshine:users /mnt/sunshine
    [Install]
    WantedBy = multi-user.target
  permissions: '0644'

runcmd:
  - systemctl enable mnt
  - wget https://github.com/LizardByte/Sunshine/releases/download/v0.16.0/sunshine-22.04.deb
  - apt-get install -y ./sunshine-22.04.deb
  - su -c "systemctl --user enable sunshine" sunshine