#cloud-config

bootcmd:
  - dpkg --add-architecture i386
  - wget http://repo.steampowered.com/steam/archive/stable/steam.gpg -P /usr/share/keyrings/

apt:
  preserve_sources_list: false
  sources:
    steam-stable.list:
      source: |
        deb [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https://repo.steampowered.com/steam/ stable steam
        deb-src [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https://repo.steampowered.com/steam/ stable steam
  conf: |
    APT {
      Install-Suggests "0";
      Install-Recommends "0";
    }

package_update: true
packages:
- adwaita-icon-theme
- alsa-utils
- baobab
- build-essential
- dkms
- dmz-cursor-theme
- gdm3
- gedit
- gnome-control-center
- gnome-session
- gnome-shell-extension-appindicator
- gnome-terminal
- httpie
- libc6-dev
- libcanberra-pulse
- libglvnd-dev
- libva-drm2
- libva2
- libvdpau1
- libvulkan1
- linux-aws
- linux-headers-aws
- nautilus
- pkg-config
- pulseaudio
- pulseaudio-module-gsettings
- restic
- steam-launcher
- steam-libs-amd64
- unzip
- ubuntu-drivers-common
- xdg-desktop-portal-gtk
- xdg-utils
- xserver-xorg-core
- xserver-xorg-dev
- xserver-xorg-input-libinput

mounts:
- ["/dev/instance-storage", "/mnt", "ext4", "defaults,nofail,x-systemd.requires=cloud-init.service,x-systemd.makefs", "0", "2"]

users:
- default
- name: sunshine
  gecos: Sunshine
  groups: users, audio, video, plugdev, netdev, input
  shell: /bin/bash

write_files:
- path: /etc/modprobe.d/blacklist.conf
  content: |
    blacklist vga16fb
    blacklist nouveau
    blacklist rivafb
    blacklist nvidiafb
    blacklist rivatv
- path: /etc/modprobe.d/nvidia.conf
  content: |
    options nvidia NVreg_EnableGpuFirmware=0
- path: /etc/gdm3/custom.conf
  content: |
    [daemon]
    WaylandEnable=false
    AutomaticLoginEnable = true
    AutomaticLogin = sunshine
    [security]
    [xdmcp]
    [chooser]
    [debug]
- path: /etc/udev/rules.d/85-sunshine-input.rules
  content: |
    KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
- path: /etc/udev/rules.d/99-ec2-cloud-storage.rules
  content: |
    KERNEL=="nvme[0-9]*n[0-9]*", ENV{DEVTYPE}=="disk", ATTRS{model}=="Amazon EC2 NVMe Instance Storage", ATTRS{serial}=="?*", SYMLINK+="instance-storage"
- path: /opt/sunshine_systemd_user_service.patch
  content: |
    5,7c5
    < PartOf=graphical-session.target
    < Wants=xdg-desktop-autostart.target
    < After=xdg-desktop-autostart.target
    ---
    > After=graphical-session.target
    15c13
    < WantedBy=xdg-desktop-autostart.target
    ---
    > WantedBy=graphical-session.target
- path: /opt/install_nvidia_driver.sh
  content: |
    #!/bin/bash
    set -euo pipefail
    ubuntu-drivers install
    test -f /etc/X11/xorg.conf || nvidia-xconfig --preserve-busid --enable-all-gpus
    nvidia-smi -q | head
  permissions: '0755'
- path: /etc/systemd/system/init_mnt.service
  content: |
    [Unit]
    After = network-online.target
    Wants = network-online.target
    RequiresMountsFor = /mnt
    [Service]
    Type = oneshot
    RemainAfterExit = yes
    ExecStart = mkdir -p /mnt/sunshine
    ExecStart = chown sunshine:sunshine /mnt/sunshine
    [Install]
    WantedBy = multi-user.target
- path: /home/ubuntu/.bash_history
  content: |
    sudo reboot
    sudo /opt/install_nvidia_driver.sh
    tail  -f /var/log/cloud-init.log
  owner: ubuntu:ubuntu
  permissions: '0600'
  defer: true
- path: /usr/lib/systemd/user/init_desktop_settings.service
  content: |
    [Unit]
    Description=Init desktop settings
    [Service]
    Type = oneshot
    RemainAfterExit = yes
    ExecStart=/usr/bin/gnome-extensions enable ubuntu-appindicators@ubuntu.com
    ExecStart=/usr/bin/gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/ubuntu-default-greyscale-wallpaper.png"
    ExecStart=/usr/bin/gsettings set org.gnome.desktop.interface enable-hot-corners false
    [Install]
    WantedBy=graphical-session.target
  permissions: '0644'
- path: /etc/profile.d/restic.sh
  content: |
    #!/bin/sh
    REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -oP '(?<="region" : ")[^"]*')
    export RESTIC_REPOSITORY=s3:https://s3.${REGION}.amazonaws.com/ec2-gaming-sunshine-library
    export RESTIC_PASSWORD=sunshine
  permissions: '0644'
- path: /usr/local/bin/backup
  content: |
    #!/bin/sh
    restic snapshots || restic init
    restic backup /mnt/sunshine
  permissions: '0755'
  defer: true
- path: /usr/local/bin/restore
  content: |
    #!/bin/sh
    restic snapshots && \
      restic restore latest -v --target / --host $(hostname -s)
    read -p "press any key"
  permissions: '0755'
  defer: true
- path: /usr/local/share/applications/restore.desktop
  content: |
    [Desktop Entry]
    Type=Application
    Name=Restore
    Exec=/usr/local/bin/restore
    Terminal=true
  permissions: '0644'
  defer: true
- path: /usr/local/share/applications/backup.desktop
  content: |
    [Desktop Entry]
    Type=Application
    Name=Backup
    Exec=/usr/local/bin/backup
    Terminal=true
  permissions: '0644'
  defer: true

runcmd:
  - systemctl enable init_mnt
  - rm -f /etc/apt/sources.list.d/steam.list
  - ubuntu-drivers install
  - apt update
  - apt install -y libc6:i386 libegl1:amd64 libegl1:i386 libgbm1:amd64 libgbm1:i386 libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1:amd64 libgl1:i386 libnvidia-gl-535:i386 steam-libs-i386:i386
  - wget https://github.com/LizardByte/Sunshine/releases/download/v0.23.1/sunshine-ubuntu-24.04-amd64.deb
  - apt install -y ./sunshine-ubuntu-24.04-amd64.deb
  - rm -f ./sunshine-ubuntu-24.04-amd64.deb
  - patch /usr/lib/systemd/user/sunshine.service < /opt/sunshine_systemd_user_service.patch
  - su -c "systemctl --user enable sunshine" sunshine
  - su -c "systemctl --user enable init_desktop_settings" sunshine
  - su -c "desktop-file-install --dir=/home/sunshine/.config/autostart /usr/local/share/applications/restore.desktop" sunshine
  - wget https://github.com/lutris/lutris/releases/download/v0.5.18/lutris_0.5.18_all.deb
  - apt install -y ./lutris_0.5.18_all.deb
  - rm -f ./lutris_0.5.18_all.deb
  - apt install -y wine64 wine32 libasound2-plugins:i386 libsdl2-2.0-0:i386 libdbus-1-3:i386 libsqlite3-0:i386
