#cloud-config

bootcmd:
  - dpkg --add-architecture i386
  - wget http://repo.steampowered.com/steam/archive/stable/steam.gpg -P /usr/share/keyrings/

apt:
  preserve_sources_list: false
  sources:
    steam-stable.list:
      source: |
        deb [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https://repo.steampowered.com/steam/ stable steam
        deb-src [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https://repo.steampowered.com/steam/ stable steam
  conf: |
    APT {
      Install-Suggests "0";
      Install-Recommends "0";
    }

package_update: true
packages:
- adwaita-icon-theme-full
- alsa-utils
- awscli
- baobab
- build-essential
- dkms
- dmz-cursor-theme
- gdm3
- gnome-control-center
- gnome-session
- gnome-shell-extension-appindicator
- gnome-terminal
- httpie
- libc6-dev
- libcanberra-pulse
- libglvnd-dev
- libva-drm2
- libva2
- libvdpau1
- libvulkan1
- linux-aws
- linux-headers-aws
- nautilus
- pkg-config
- pulseaudio
- pulseaudio-module-gsettings
- restic
- steam-launcher
- steam-libs-amd64
- steam-libs-i386:i386
- unzip
- xdg-desktop-portal-gtk
- xdg-utils
- xserver-xorg-core
- xserver-xorg-dev
- xserver-xorg-input-libinput

# required on first boot only
fs_setup:
- label: instance_storage
  device: /dev/nvme1n1
  filesystem: ext4

mounts:
- ["/dev/nvme1n1", "/mnt", "ext4", "defaults,nofail,x-systemd.requires=cloud-init.service,x-systemd.makefs", "0", "2"]

users:
- default
- name: sunshine
  gecos: Sunshine
  groups: users, audio, video, plugdev, netdev, input
  shell: /bin/bash

write_files:
- path: /etc/modprobe.d/blacklist.conf
  content: |
    blacklist vga16fb
    blacklist nouveau
    blacklist rivafb
    blacklist nvidiafb
    blacklist rivatv
- path: /etc/modprobe.d/nvidia.conf
  content: |
    options nvidia NVreg_EnableGpuFirmware=0
- path: /etc/gdm3/custom.conf
  content: |
    [daemon]
    WaylandEnable=false
    AutomaticLoginEnable = true
    AutomaticLogin = sunshine
    [security]
    [xdmcp]
    [chooser]
    [debug]
- path: /etc/udev/rules.d/85-sunshine-input.rules
  content: |
    KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
- path: /opt/install_nvidia_driver.sh
  content: |
    #!/bin/bash
    cd /mnt
    aws s3 cp --recursive s3://nvidia-gaming/linux/latest/ .
    unzip *Cloud_Gaming-Linux-Guest-Drivers.zip -d nvidia-drivers
    rm -f *Cloud_Gaming-Linux-Guest-Drivers.zip
    chmod +x ./nvidia-drivers/NVIDIA-Linux-x86_64*-grid.run
    /bin/sh ./nvidia-drivers/NVIDIA-Linux-x86_64*-grid.run --dkms --tmpdir=/mnt --silent
    rm -rf ./nvidia-drivers/
    kversion=$(readlink /boot/initrd.img |sed 's/initrd.img-//g')
    dkms autoinstall -k $kversion
    update-initramfs -k $kversion -u
    cat << EOF | tee -a /etc/nvidia/gridd.conf
    vGamingMarketplace=2
    EOF
    curl -o /etc/nvidia/GridSwCert.txt "https://nvidia-gaming.s3.amazonaws.com/GridSwCert-Archive/GridSwCertLinux_2021_10_2.cert"
    nvidia-smi -q | head
    nvidia-xconfig --preserve-busid --enable-all-gpus
  permissions: '0755'
- path: /etc/systemd/system/init_mnt.service
  content: |
    [Unit]
    After = network-online.target
    Wants = network-online.target
    [Service]
    Type = oneshot
    RemainAfterExit = yes
    ExecStart = mkdir -p /mnt/sunshine
    ExecStart = chown sunshine:sunshine /mnt/sunshine
    [Install]
    WantedBy = multi-user.target
- path: /home/ubuntu/.bash_history
  content: |
    sudo reboot
    sudo /opt/install_nvidia_driver.sh
    tail  -f /var/log/cloud-init.log
  owner: ubuntu:ubuntu
  permissions: '0600'
  defer: true
- path: /usr/lib/systemd/user/init_desktop_settings.service
  content: |
    [Unit]
    Description=Init desktop settings
    [Service]
    Type = oneshot
    RemainAfterExit = yes
    ExecStart=/usr/bin/gnome-extensions enable ubuntu-appindicators@ubuntu.com
    ExecStart=/usr/bin/gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/Jammy-Jellyfish_WP_4096x2304_Grey.png"
    ExecStart=/usr/bin/gsettings set org.gnome.desktop.interface enable-hot-corners false
    [Install]
    WantedBy=graphical-session.target
  permissions: '0644'
- path: /etc/profile.d/restic.sh
  content: |
    #!/bin/sh
    export RESTIC_REPOSITORY=s3:https://s3.eu-central-1.amazonaws.com/jammy-sunshine-library
    export RESTIC_PASSWORD=sunshine
  permissions: '0644'
- path: /usr/local/bin/backup
  content: |
    #!/bin/sh
    restic snapshots || restic init
    restic backup /mnt/sunshine
  permissions: '0755'
  defer: true
- path: /usr/local/bin/restore
  content: |
    #!/bin/sh
    restic snapshots && \
      restic restore latest -v --target / --host $(hostname -s)
    read -p "press any key"
  permissions: '0755'
  defer: true
- path: /usr/local/share/applications/restore.desktop
  content: |
    [Desktop Entry]
    Type=Application
    Name=Restore
    Exec=/usr/local/bin/restore
    Terminal=true
  permissions: '0644'
  defer: true
- path: /usr/local/share/applications/backup.desktop
  content: |
    [Desktop Entry]
    Type=Application
    Name=Backup
    Exec=/usr/local/bin/backup
    Terminal=true
  permissions: '0644'
  defer: true

runcmd:
  - systemctl enable init_mnt
  - wget https://github.com/LizardByte/Sunshine/releases/download/v0.18.4/sunshine-ubuntu-22.04-amd64.deb
  - apt-get install -y ./sunshine-ubuntu-22.04-amd64.deb
  - su -c "systemctl --user enable sunshine" sunshine
  - su -c "systemctl --user enable init_desktop_settings" sunshine
  - su -c "desktop-file-install --dir=/home/sunshine/.config/autostart /usr/local/share/applications/restore.desktop" sunshine
  - wget https://github.com/lutris/lutris/releases/download/v0.5.14/lutris_0.5.14_all.deb
  - apt-get install -y ./lutris_0.5.14_all.deb
