AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ParentStackName:
    Type: "String"
  SecurityGroups:
    Type: "List<AWS::EC2::SecurityGroup::Id>"
  Subnet1:
    Type: "AWS::EC2::Subnet::Id"
  LatestAmi:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id"
  KeyPair:
    Description: EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
  InstanceProfileArn:
    Type: "String"

Resources:
  OnDemandLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Sub "${ParentStackName}-noble-on-demand"
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref Subnet1
          Groups: !Ref SecurityGroups
        PrivateDnsNameOptions:
          HostnameType: resource-name
        BlockDeviceMappings:
        - Ebs:
            VolumeSize: 20
            VolumeType: gp2
            DeleteOnTermination: true
            Encrypted: true
          DeviceName: /dev/sda1
        ImageId: !Ref LatestAmi
        InstanceType: g4dn.xlarge
        KeyName: !Ref KeyPair
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${ParentStackName}-instance"
              - Key: Distribution
                Value: Ubuntu
              - Key: Release
                Value: 24.04
              - Key: Codename
                Value: noble
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: launch-templates-noble-userdata.yaml
  SpotLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Sub "${ParentStackName}-noble-spot"
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            DeleteOnTermination: true
            SubnetId: !Ref Subnet1
            Groups: !Ref SecurityGroups
        PrivateDnsNameOptions:
          HostnameType: resource-name
        BlockDeviceMappings:
          - Ebs:
              VolumeSize: 20
              VolumeType: gp2
              DeleteOnTermination: true
              Encrypted: true
            DeviceName: /dev/sda1
        ImageId: !Ref LatestAmi
        InstanceType: g4dn.xlarge
        KeyName: !Ref KeyPair
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            InstanceInterruptionBehavior: stop
            SpotInstanceType: persistent
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${ParentStackName}-instance"
              - Key: Distribution
                Value: Ubuntu
              - Key: Release
                Value: 24.04
              - Key: Codename
                Value: noble
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: launch-templates-noble-userdata.yaml

Outputs:
  OnDemandLaunchTemplate:
    Description: On-demand instance launch template
    Value: !Ref OnDemandLaunchTemplate
  SpotLaunchTemplate:
    Description: Spot instance launch template
    Value: !Ref SpotLaunchTemplate

# vim: ft=yaml.cloudformation
