name: CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          mkdir -p dist
          python deploy.py --print-only > dist/ec2-gaming-sunshine.template
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: lint
        run: |
          ruff check .
  release:
    needs: [build, lint]
    if: ${{ github.event_name != 'pull_request' }}
    concurrency: release
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: python-semantic-release/python-semantic-release@v9
        id: release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false
      - uses: python-semantic-release/publish-action@v9
        id: publish
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
