name: CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: lint Python code
        run: |
          ruff check .
      - name: run tests with coverage
        run: |
          coverage run -m unittest discover tests
      - name: generate coverage report
        run: |
          coverage report -m
      - name: validate AWS SAM template
        run: |
          sam validate --lint
      - name: lint CloudFormation templates
        run: |
          cfn-lint cloudformation/*
  release:
    needs: [test]
    if: ${{ github.event_name != 'pull_request' }}
    concurrency: release
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: python-semantic-release/python-semantic-release@v10
        id: release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false
          push: true
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
